databases:
  - name: deltaa
    databaseName: deltaa
    user: deltaa_user

services:
  - type: web
    name: todo
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: deltaa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false